# Generated by Django 5.0.7 on 2026-02-02 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='fleet.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LATE_RETURN', 'Late return'), ('BAD_CONDITION', 'Bad condition')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='rentals.rentalagreement')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RENTAL_CHARGE', 'Rental charge'), ('DEPOSIT_HELD', 'Deposit held'), ('DEPOSIT_REFUND', 'Deposit refund'), ('PENALTY_CHARGE', 'Penalty charge')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rentals.rentalagreement')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partial refund'), ('FORFEITED', 'Forfeited')], default='HELD', max_length=20)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='rentals.rentalagreement')),
            ],
        ),
    ]
